//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_ItemLanguage
    {
        public System.Guid ItemID { get; set; }
        public int LanguageType { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string TemplateText { get; set; }
        public string CustomFormatText { get; set; }
        public string LinkUrl { get; set; }
        public bool IsBlankUrl { get; set; }
        public string Keywords { get; set; }
        public string Author { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string AddressInfo { get; set; }
        public string DiscountText { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual cms_Item cms_Item { get; set; }
    }
}
