//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_Email()
        {
            this.cms_EmailSendUser = new HashSet<cms_EmailSendUser>();
        }
    
        public System.Guid ID { get; set; }
        public int SeqNo { get; set; }
        public System.Guid ClientID { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string FilePaths { get; set; }
        public int SystemMailType { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.Guid> SendUser { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_EmailSendUser> cms_EmailSendUser { get; set; }
        public virtual mgt_User mgt_User { get; set; }
        public virtual mgt_User mgt_User1 { get; set; }
        public virtual mgt_Client mgt_Client { get; set; }
    }
}
