//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Structure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_Structure()
        {
            this.cms_ItemFile = new HashSet<cms_ItemFile>();
            this.ChildStructures = new HashSet<cms_Structure>();
            this.ParentStructure = new HashSet<cms_Structure>();
            this.cms_Item = new HashSet<cms_Item>();
            this.erp_Order = new HashSet<erp_Order>();
            this.cms_EmailTemplate = new HashSet<cms_EmailTemplate>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ClientID { get; set; }
        public int SeqNo { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Template { get; set; }
        public string CustomFormat { get; set; }
        public int DefaultLanguage { get; set; }
        public string LanguageTypes { get; set; }
        public int ParentRelationType { get; set; }
        public int ChildRelationType { get; set; }
        public string ToolTypes { get; set; }
        public string ContentTypes { get; set; }
        public string RequiredTypes { get; set; }
        public string FilterTypes { get; set; }
        public string ListTypes { get; set; }
        public string ContentLanguageTypes { get; set; }
        public string FileTypes { get; set; }
        public string FileToolTypes { get; set; }
        public int ImageWidth { get; set; }
        public int ImageHeight { get; set; }
        public string OrderName { get; set; }
        public string PayTypes { get; set; }
        public string DeliveryTypes { get; set; }
        public string OrderStatuses { get; set; }
        public string OrderContentTypes { get; set; }
        public int OrderErrorReturnPage { get; set; }
        public string ItemTypes { get; set; }
        public string ViewName { get; set; }
        public int Sort { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string DiscountTypes { get; set; }
        public string PriceTypes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_ItemFile> cms_ItemFile { get; set; }
        public virtual mgt_Client mgt_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Structure> ChildStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Structure> ParentStructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Item> cms_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_Order> erp_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_EmailTemplate> cms_EmailTemplate { get; set; }
    }
}
