//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebMakerDBEntities : DbContext
    {
        public WebMakerDBEntities()
            : base("name=WebMakerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mgt_SystemSetting> mgt_SystemSetting { get; set; }
        public virtual DbSet<cms_ItemFile> cms_ItemFile { get; set; }
        public virtual DbSet<mgt_UserValidCode> mgt_UserValidCode { get; set; }
        public virtual DbSet<cms_Email> cms_Email { get; set; }
        public virtual DbSet<cms_EmailSendUser> cms_EmailSendUser { get; set; }
        public virtual DbSet<mgt_UserExternalLogin> mgt_UserExternalLogin { get; set; }
        public virtual DbSet<mgt_Role> mgt_Role { get; set; }
        public virtual DbSet<mgt_Menu> mgt_Menu { get; set; }
        public virtual DbSet<mgt_RoleMenuRelation> mgt_RoleMenuRelation { get; set; }
        public virtual DbSet<cms_ItemLanguage> cms_ItemLanguage { get; set; }
        public virtual DbSet<erp_OrderLog> erp_OrderLog { get; set; }
        public virtual DbSet<cms_ItemRelation> cms_ItemRelation { get; set; }
        public virtual DbSet<mgt_UserLog> mgt_UserLog { get; set; }
        public virtual DbSet<mgt_Department> mgt_Department { get; set; }
        public virtual DbSet<mgt_User> mgt_User { get; set; }
        public virtual DbSet<mgt_Client> mgt_Client { get; set; }
        public virtual DbSet<cms_Structure> cms_Structure { get; set; }
        public virtual DbSet<mgt_UserProfile> mgt_UserProfile { get; set; }
        public virtual DbSet<cms_Item> cms_Item { get; set; }
        public virtual DbSet<cms_ItemOrderRoleRelation> cms_ItemOrderRoleRelation { get; set; }
        public virtual DbSet<mgt_UserRoleRelation> mgt_UserRoleRelation { get; set; }
        public virtual DbSet<erp_OrderDiscount> erp_OrderDiscount { get; set; }
        public virtual DbSet<erp_Order> erp_Order { get; set; }
        public virtual DbSet<erp_GetPayMessage> erp_GetPayMessage { get; set; }
        public virtual DbSet<erp_OrderDetail> erp_OrderDetail { get; set; }
        public virtual DbSet<erp_OrderUnit> erp_OrderUnit { get; set; }
        public virtual DbSet<cms_EmailTemplate> cms_EmailTemplate { get; set; }
        public virtual DbSet<cms_SmsLog> cms_SmsLog { get; set; }
        public virtual DbSet<mgt_UserAssign> mgt_UserAssign { get; set; }
    }
}
