//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erp_OrderDetail()
        {
            this.erp_OrderDiscount = new HashSet<erp_OrderDiscount>();
            this.TeamMembers = new HashSet<mgt_UserProfile>();
            this.erp_OrderUnit = new HashSet<erp_OrderUnit>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid ItemID { get; set; }
        public string ItemSubject { get; set; }
        public string Option { get; set; }
        public string DetailTeamName { get; set; }
        public string FilePath { get; set; }
        public decimal SalePrice { get; set; }
        public int Quantity { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.Guid> CombineOriOrderID { get; set; }
    
        public virtual cms_Item cms_Item { get; set; }
        public virtual erp_Order erp_Order { get; set; }
        public virtual erp_Order erp_OrderCombineOri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderDiscount> erp_OrderDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> TeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderUnit> erp_OrderUnit { get; set; }
    }
}
