//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_OrderDiscount
    {
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public Nullable<System.Guid> OrderDetailID { get; set; }
        public System.Guid DiscountID { get; set; }
        public decimal DiscountPrice { get; set; }
    
        public virtual cms_Item cms_Item { get; set; }
        public virtual erp_Order erp_Order { get; set; }
        public virtual erp_OrderDetail erp_OrderDetail { get; set; }
    }
}
