//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erp_Order()
        {
            this.FromCombineOrder = new HashSet<erp_Order>();
            this.erp_OrderDiscount = new HashSet<erp_OrderDiscount>();
            this.erp_OrderLog = new HashSet<erp_OrderLog>();
            this.TeamMembers = new HashSet<mgt_UserProfile>();
            this.mgt_UserRoleRelation = new HashSet<mgt_UserRoleRelation>();
            this.erp_GetPayMessage = new HashSet<erp_GetPayMessage>();
            this.erp_OrderDetail = new HashSet<erp_OrderDetail>();
            this.erp_OrderDetailCombines = new HashSet<erp_OrderDetail>();
            this.erp_OrderUnit = new HashSet<erp_OrderUnit>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ClientID { get; set; }
        public System.Guid StructureID { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public string OrderNumber { get; set; }
        public int PayType { get; set; }
        public string PayInfo { get; set; }
        public int DeliveryType { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverAddres { get; set; }
        public string ReceiverEmail { get; set; }
        public string TeamName { get; set; }
        public string Coach { get; set; }
        public string Leader { get; set; }
        public string Manager { get; set; }
        public string OrderNote { get; set; }
        public string FilePath { get; set; }
        public string PublicNote { get; set; }
        public string PrivateNote { get; set; }
        public decimal DetailPrice { get; set; }
        public decimal ShippingFee { get; set; }
        public decimal TotalPrice { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUser { get; set; }
        public string VirtualAccount { get; set; }
        public Nullable<System.DateTime> VirtualCreateTime { get; set; }
        public Nullable<System.DateTime> PayDeadline { get; set; }
        public Nullable<System.Guid> CombineOrderID { get; set; }
        public Nullable<System.DateTime> EditDeadline { get; set; }
    
        public virtual cms_Item cms_Item { get; set; }
        public virtual cms_Structure cms_Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_Order> FromCombineOrder { get; set; }
        public virtual erp_Order ToCombineOrder { get; set; }
        public virtual mgt_Client mgt_Client { get; set; }
        public virtual mgt_User mgt_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderDiscount> erp_OrderDiscount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderLog> erp_OrderLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> TeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserRoleRelation> mgt_UserRoleRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_GetPayMessage> erp_GetPayMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderDetail> erp_OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderDetail> erp_OrderDetailCombines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderUnit> erp_OrderUnit { get; set; }
    }
}
