//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_OrderUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public erp_OrderUnit()
        {
            this.mgt_UserProfile = new HashSet<mgt_UserProfile>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public string Unit { get; set; }
        public string UnitShort { get; set; }
        public string County { get; set; }
        public string Coach { get; set; }
        public string Leader { get; set; }
        public string Manager { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUser { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Sort { get; set; }
        public int TempNo { get; set; }
        public bool IsKeep { get; set; }
        public Nullable<System.Guid> OrderDetailID { get; set; }
    
        public virtual erp_Order erp_Order { get; set; }
        public virtual mgt_User mgt_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> mgt_UserProfile { get; set; }
        public virtual erp_OrderDetail erp_OrderDetail { get; set; }
    }
}
