//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class erp_GetPayMessage
    {
        public long SeqNo { get; set; }
        public System.Guid ClientID { get; set; }
        public string OriData { get; set; }
        public string DecryptData { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public int PayType { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool IsByQuery { get; set; }
        public bool IsEnabled { get; set; }
        public string VirtualAccount { get; set; }
    
        public virtual erp_Order erp_Order { get; set; }
        public virtual mgt_Client mgt_Client { get; set; }
    }
}
