//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_RoleMenuRelation
    {
        public System.Guid RoleID { get; set; }
        public System.Guid MenuID { get; set; }
        public string RoleActions { get; set; }
    
        public virtual mgt_Menu mgt_Menu { get; set; }
        public virtual mgt_Role mgt_Role { get; set; }
    }
}
