//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mgt_Client()
        {
            this.cms_Email = new HashSet<cms_Email>();
            this.mgt_Department = new HashSet<mgt_Department>();
            this.mgt_Role = new HashSet<mgt_Role>();
            this.mgt_SystemSetting = new HashSet<mgt_SystemSetting>();
            this.cms_Structure = new HashSet<cms_Structure>();
            this.cms_Item = new HashSet<cms_Item>();
            this.erp_Order = new HashSet<erp_Order>();
            this.erp_GetPayMessage = new HashSet<erp_GetPayMessage>();
            this.cms_EmailTemplate = new HashSet<cms_EmailTemplate>();
            this.cms_SmsLog = new HashSet<cms_SmsLog>();
            this.mgt_UserProfile = new HashSet<mgt_UserProfile>();
        }
    
        public System.Guid ID { get; set; }
        public int SeqNo { get; set; }
        public string SystemName { get; set; }
        public string ClientCode { get; set; }
        public string AdminRoute { get; set; }
        public string WebsiteUrl { get; set; }
        public int DefaultLanguage { get; set; }
        public string FrontLanguageTypes { get; set; }
        public string BackLanguageTypes { get; set; }
        public string ClientSetting { get; set; }
        public int Sort { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Email> cms_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_Department> mgt_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_Role> mgt_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_SystemSetting> mgt_SystemSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Structure> cms_Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Item> cms_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_Order> erp_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_GetPayMessage> erp_GetPayMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_EmailTemplate> cms_EmailTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_SmsLog> cms_SmsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> mgt_UserProfile { get; set; }
    }
}
