//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_UserRoleRelation
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid RoleID { get; set; }
        public string RoleNumber { get; set; }
        public bool IsTimeLimited { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual mgt_Role mgt_Role { get; set; }
        public virtual mgt_User mgt_User { get; set; }
        public virtual erp_Order erp_Order { get; set; }
    }
}
