//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mgt_User()
        {
            this.cms_Email = new HashSet<cms_Email>();
            this.cms_Email1 = new HashSet<cms_Email>();
            this.cms_EmailSendUser = new HashSet<cms_EmailSendUser>();
            this.cms_ItemFile = new HashSet<cms_ItemFile>();
            this.erp_OrderLog = new HashSet<erp_OrderLog>();
            this.mgt_UserExternalLogin = new HashSet<mgt_UserExternalLogin>();
            this.mgt_UserLog = new HashSet<mgt_UserLog>();
            this.mgt_UserValidCode = new HashSet<mgt_UserValidCode>();
            this.mgt_UserLog1 = new HashSet<mgt_UserLog>();
            this.cms_Item = new HashSet<cms_Item>();
            this.cms_Item1 = new HashSet<cms_Item>();
            this.mgt_UserRoleRelation = new HashSet<mgt_UserRoleRelation>();
            this.erp_Order = new HashSet<erp_Order>();
            this.mgt_UserProfile1 = new HashSet<mgt_UserProfile>();
            this.erp_OrderUnit = new HashSet<erp_OrderUnit>();
            this.cms_EmailTemplate = new HashSet<cms_EmailTemplate>();
            this.cms_SmsLog = new HashSet<cms_SmsLog>();
            this.mgt_UserAssign = new HashSet<mgt_UserAssign>();
            this.mgt_UserAssign1 = new HashSet<mgt_UserAssign>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> UserProfileID { get; set; }
        public System.Guid ClientID { get; set; }
        public string SystemNumber { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public bool EmailIsVerify { get; set; }
        public bool IsReceiveEpaper { get; set; }
        public string Phone { get; set; }
        public bool PhoneIsVerify { get; set; }
        public string ZipCodeOption { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public int AccountType { get; set; }
        public string LoginTypes { get; set; }
        public int UserStatus { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastLoginIP { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Email> cms_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Email> cms_Email1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_EmailSendUser> cms_EmailSendUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_ItemFile> cms_ItemFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderLog> erp_OrderLog { get; set; }
        public virtual mgt_Department mgt_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserExternalLogin> mgt_UserExternalLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserLog> mgt_UserLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserValidCode> mgt_UserValidCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserLog> mgt_UserLog1 { get; set; }
        public virtual mgt_UserProfile mgt_UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Item> cms_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Item> cms_Item1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserRoleRelation> mgt_UserRoleRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_Order> erp_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> mgt_UserProfile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderUnit> erp_OrderUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_EmailTemplate> cms_EmailTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_SmsLog> cms_SmsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserAssign> mgt_UserAssign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserAssign> mgt_UserAssign1 { get; set; }
    }
}
