//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mgt_UserProfile()
        {
            this.mgt_User = new HashSet<mgt_User>();
            this.erp_OrderDetail = new HashSet<erp_OrderDetail>();
            this.mgt_UserProfileCopies = new HashSet<mgt_UserProfile>();
            this.mgt_UserAssign = new HashSet<mgt_UserAssign>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string EngName { get; set; }
        public string NickName { get; set; }
        public string AvatarPath { get; set; }
        public string Description { get; set; }
        public string HouseholdAddress { get; set; }
        public string IdentityCard { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int Gender { get; set; }
        public int Marriage { get; set; }
        public string HomePhone { get; set; }
        public string CompanyPhone { get; set; }
        public string SecondaryEmail { get; set; }
        public string EmergencyContact { get; set; }
        public string EmergencyPhone { get; set; }
        public string Unit { get; set; }
        public string UnitAddress { get; set; }
        public string Occupation { get; set; }
        public string Education { get; set; }
        public string School { get; set; }
        public string Skill { get; set; }
        public string Language { get; set; }
        public string Sports { get; set; }
        public string SocialNetwork { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Referrer { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UnitShort { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public int Sort { get; set; }
        public int TempNo { get; set; }
        public bool IsKeep { get; set; }
        public Nullable<System.Guid> UnitID { get; set; }
        public bool IsPassportNumber { get; set; }
        public bool IsMyChild { get; set; }
        public System.Guid ClientID { get; set; }
        public Nullable<System.Guid> FromSourceID { get; set; }
        public bool IsDelete { get; set; }
        public bool IsSend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_User> mgt_User { get; set; }
        public virtual cms_Item cms_Item { get; set; }
        public virtual erp_Order erp_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<erp_OrderDetail> erp_OrderDetail { get; set; }
        public virtual mgt_User mgt_UserCreate { get; set; }
        public virtual erp_OrderUnit erp_OrderUnit { get; set; }
        public virtual mgt_Client mgt_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserProfile> mgt_UserProfileCopies { get; set; }
        public virtual mgt_UserProfile mgt_UserProfileSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mgt_UserAssign> mgt_UserAssign { get; set; }
    }
}
