//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_UserAssign
    {
        public System.Guid ID { get; set; }
        public System.Guid UserProfileID { get; set; }
        public System.Guid FromUser { get; set; }
        public System.Guid ToUser { get; set; }
        public string Note { get; set; }
        public int Sort { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual mgt_User mgt_UserFrom { get; set; }
        public virtual mgt_User mgt_UserTo { get; set; }
        public virtual mgt_UserProfile mgt_UserProfile { get; set; }
    }
}
