//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaker.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mgt_UserLog
    {
        public long SeqNo { get; set; }
        public System.Guid UserID { get; set; }
        public int UserLogType { get; set; }
        public string ModelName { get; set; }
        public string DataContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.Guid CreateUser { get; set; }
    
        public virtual mgt_User mgt_User { get; set; }
        public virtual mgt_User mgt_User1 { get; set; }
    }
}
